### ISSUE TITLE
SIGSEGV on shutdown

### ISSUE THREAD

**Issue by OPNA2608** [solemnwarning/rehex#195]
Latest master, x86_64-linux.

```
Thread 1 "rehex" received signal SIGSEGV, Segmentation fault.
0x0000000000000271 in ?? ()
(gdb) bt
#0  0x0000000000000271 in ?? ()
#1  0x00007ffff7bfefd9 in wxAppConsoleBase::CleanUp() () from /nix/store/8w1ckqq237kkqi39x7l9i9c4b0rk590m-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#2  0x00007ffff7c7e8ce in wxEntryCleanup() () from /nix/store/8w1ckqq237kkqi39x7l9i9c4b0rk590m-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#3  0x00007ffff7c7f29a in wxEntry(int&, wchar_t**) () from /nix/store/8w1ckqq237kkqi39x7l9i9c4b0rk590m-wxwidgets-3.2.1/lib/libwx_baseu-3.2.so.0
#4  0x00000000004bfd96 in main (argc=<optimized out>, argv=<optimized out>) at src/AppMain.cpp:41
```

Only seems to happen with wxGTK 3.2, doesn't crash on wxGTK 3.1 or wxGTK 3.0 (which your AppImage uses).

**Comment by OPNA2608** [comment]
Hmm, seems to have resolved itself when I tried to mess around with it… Sorry for the noise!
